In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [2]:
a = np.empty((3,3,3))
print(a)

[[[5.61858287e+175 1.05854545e+200 1.46921998e+195]
  [3.02876088e-152 5.83439491e+252 5.81236387e+180]
  [4.20715265e+251 3.15474910e+180 2.31463017e-152]]

 [[2.30908182e+251 2.79194220e-152 5.28961029e+180]
  [4.71980621e+164 5.53194614e+199 4.27255602e+180]
  [3.17095856e+180 2.43395994e-152 3.17095864e+180]]

 [[6.96412858e+252 1.96086529e+243 5.02070164e+276]
  [3.15474910e+180 2.43395994e-152 7.62870122e+228]
  [7.10236516e+194 1.46923551e+195 2.03631957e+174]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
b = np.zeros((5,5))
count = 1;
for i in range(5):
    for j in range(5):
        if i == j and j-1 >= 0:
            b[i][j-1] = count;
            count = count + 1
print(b)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
c = np.zeros((8,8), dtype = 'int32')
c[1::2, ::2] = 1
c[::2, 1::2] = 1
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [3]:
d = np.empty((5,5))
print(d)

dmax = d.max()
dmin = d.min()

d = (d - dmin)/(dmax - dmin)

print(d)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.01092457e-307
  1.89146896e-307]
 [1.37961302e-306 1.05699242e-307 8.01097889e-307 1.78020169e-306
  7.56601165e-307]
 [1.02359984e-306 1.33510679e-306 2.22522597e-306 1.24611674e-306
  1.29061821e-306]
 [6.23057349e-307 2.22522597e-306 1.06810268e-306 6.23052935e-307
  1.29062025e-306]
 [8.34445562e-308 1.78022342e-306 8.06635958e-308 1.42410974e-306
  3.20558931e-317]]
[[0.27999047 0.20999968 0.76001763 0.36000499 0.08500121]
 [0.61998783 0.04750045 0.36000743 0.8000094  0.34001094]
 [0.45999816 0.59998706 1.         0.55999559 0.57999423]
 [0.27999734 1.         0.4799974  0.27999536 0.57999514]
 [0.03749936 0.80001916 0.03624962 0.63998433 0.        ]]


# 5.  How to find common values between two arrays?

In [4]:
e = np.array([1,2,3,4,5])
f = np.array([2,4,6,8,10])

print(np.intersect1d(e,f))

[2 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [5]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday -", yesterday)

today = np.datetime64('today', 'D')
print("Today -",today)

tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("Tomorrow -", tomorrow)

Yesterday - 2020-07-26
Today - 2020-07-27
Tomorrow - 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [7]:
arrA = np.empty((3,3))
arrB = np.empty((3,3))

print(arrA)
print()
print(arrB)

bool_arr = arrA == arrB
print(bool_arr)

if False in bool_arr:
    print("\nBoth the arrays are not equal")
else:
    print("\nBoth the arrays are equal")

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 4.387e-321]
 [0.000e+000 0.000e+000 0.000e+000]]

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.07110092e-321]
 [1.78022341e-306 8.06635958e-308 1.42410974e-306]]
[[ True  True  True]
 [ True  True False]
 [False False False]]

Both the arrays are not equal



# 8.Create random vector of size 10 and replace the maximum value by 0 

In [44]:
vect = np.empty((10), dtype = 'int32')
print(vect)

vect.sort()
vect[vect.argmax()] = 0
print(vect)

[-1881382480         527           3           0           3           0
           1           0           0           0]
[-1881382480           0           0           0           0           0
           1           3           3           0]


# 9. How to print all the values of an array?

In [8]:
arr = np.arange(1,15,2)
print(arr)

for i in range(len(arr)):
    print(arr[i], end = " ")

[ 1  3  5  7  9 11 13]
1 3 5 7 9 11 13 

# 10.Subtract the mean of each row of a matrix

In [5]:
x = np.empty((5, 5), dtype='int32')
print(x)
y = x - x.mean(axis=1)
print()
print(y)

[[-460121080        470         50          0          0]
 [         0          0          0          0    4259932]
 [1852990827 1697541221  959984485  758604598  811743544]
 [ 858862637  809053493 1630352483 1681207654  926036326]
 [ 775250488 1952543859    7566197    6946908    6553701]]

[[-3.68096968e+08 -8.51516400e+05 -1.21617288e+09 -1.18110252e+09
  -5.49772231e+08]
 [ 9.20241120e+07 -8.51986400e+05 -1.21617294e+09 -1.18110252e+09
  -5.45512299e+08]
 [ 1.94501494e+09  1.69668923e+09 -2.56188450e+08 -4.22497921e+08
   2.61971313e+08]
 [ 9.50886749e+08  8.08201507e+08  4.14179548e+08  5.00105135e+08
   3.76264095e+08]
 [ 8.67274600e+08  1.95169187e+09 -1.20860674e+09 -1.17415561e+09
  -5.43218530e+08]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
vecta = np.ones(20)
print(vecta)

vectb = np.random.randint(0,len(vecta),20)
print(vectb)

vecta += np.bincount(vectb, minlength=len(vecta))
print(vecta)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 3 19 15  0 13  9 14 17  2  5  6 18  2 11  7  0 11 19 19  6]
[3. 1. 3. 2. 1. 2. 3. 2. 1. 2. 1. 3. 1. 2. 2. 2. 1. 2. 2. 4.]


# 12.How to get the diagonal of a dot product?

In [20]:
x = np.empty((2,2), dtype = 'int32')
y = np.empty((2,2), dtype = 'int32')

print(x)
print()
print(y)
print()

print(np.diag(x.dot(y)))

[[867103232 212640576]
 [        0         0]]

[[-465045680        470]
 [         0          0]]

[271163392         0]


# 13.How to find the most frequent value in an array?

In [28]:
freq = np.random.randint(1,12,22)
print(freq)

print(np.bincount(freq).argmax())

[ 9 11  7  9  4  4  3  2  2 11  3 11  9  5 10  3  8 11  5  9  1 10]
9


# 14.How to get the n largest values of an array

In [31]:
arr = np.random.randint(3,14,12)
print(arr)
n = 4

print(arr.argsort())
arr.argsort()[-n:][::-1]

[10  7  7 10 10  8 10  6  5 12 10  8]
[ 8  7  1  2  5 11  0  3  4  6 10  9]


array([ 9, 10,  6,  4], dtype=int64)

# 15.How to create a record array from a regular array?

In [36]:
regarr = np.random.randint(1,14,20)

print(regarr)

result = np.core.records.fromarrays(regarr)
print(result)

[13  8  7  3 13  5 11  3  7 12 12  3 10  6  9  4  9 11 13  1]
(13, 8, 7, 3, 13, 5, 11, 3, 7, 12, 12, 3, 10, 6, 9, 4, 9, 11, 13, 1)
